from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass

from backend.app.domain import IndustryRef


@dataclass(frozen=True)
class IndustryRule:
    industry_id: str
    sector_id: str
    name_zh: str
    name_en: str
    aliases: tuple[str, ...]


SECTORS = (
    IndustryRef(
        industry_id="sector:energy",
        level=1,
        name_zh="能源",
        name_en="Energy",
        aliases=["石油天然气", "oil gas"],
    ),
    IndustryRef(
        industry_id="sector:materials",
        level=1,
        name_zh="原材料",
        name_en="Materials",
        aliases=["材料", "基础化工"],
    ),
    IndustryRef(
        industry_id="sector:industrials",
        level=1,
        name_zh="工业",
        name_en="Industrials",
        aliases=["制造业", "工业制造"],
    ),
    IndustryRef(
        industry_id="sector:consumer_discretionary",
        level=1,
        name_zh="可选消费",
        name_en="Consumer Discretionary",
        aliases=["非必需消费", "consumer cyclical"],
    ),
    IndustryRef(
        industry_id="sector:consumer_staples",
        level=1,
        name_zh="必选消费",
        name_en="Consumer Staples",
        aliases=["日常消费", "consumer defensive"],
    ),
    IndustryRef(
        industry_id="sector:health_care",
        level=1,
        name_zh="医疗健康",
        name_en="Health Care",
        aliases=["医药生物", "医疗保健", "healthcare"],
    ),
    IndustryRef(
        industry_id="sector:financials",
        level=1,
        name_zh="金融",
        name_en="Financials",
        aliases=["金融服务", "金融业", "financial services"],
    ),
    IndustryRef(
        industry_id="sector:information_technology",
        level=1,
        name_zh="信息技术",
        name_en="Information Technology",
        aliases=["科技", "technology"],
    ),
    IndustryRef(
        industry_id="sector:communication_services",
        level=1,
        name_zh="通信服务",
        name_en="Communication Services",
        aliases=["传媒通信"],
    ),
    IndustryRef(
        industry_id="sector:utilities",
        level=1,
        name_zh="公用事业",
        name_en="Utilities",
        aliases=["电力公用事业"],
    ),
    IndustryRef(
        industry_id="sector:real_estate",
        level=1,
        name_zh="房地产",
        name_en="Real Estate",
        aliases=["地产"],
    ),
    IndustryRef(
        industry_id="sector:digital_assets",
        level=1,
        name_zh="数字资产",
        name_en="Digital Assets",
        aliases=["加密资产", "crypto"],
    ),
)


RULES = (
    IndustryRule(
        "industry:oil_gas",
        "sector:energy",
        "石油与天然气",
        "Oil & Gas",
        ("oil gas", "oil & gas", "石油及天然气", "石油天然气", "油气", "石油"),
    ),
    IndustryRule(
        "industry:coal", "sector:energy", "煤炭", "Coal", ("coal", "煤炭", "焦煤", "焦炭")
    ),
    IndustryRule(
        "industry:renewable_energy",
        "sector:energy",
        "新能源",
        "Renewable Energy",
        (
            "solar",
            "renewable energy",
            "clean energy",
            "光伏设备",
            "光伏",
            "风电设备",
            "风电",
            "新能源",
        ),
    ),
    IndustryRule(
        "industry:diversified_energy",
        "sector:energy",
        "综合能源",
        "Diversified Energy",
        ("energy services", "综合能源"),
    ),
    IndustryRule(
        "industry:metals_mining",
        "sector:materials",
        "金属与采矿",
        "Metals & Mining",
        (
            "other precious metals",
            "gold",
            "silver",
            "steel",
            "metals mining",
            "general metals",
            "manufacturing - metal fabrication",
            "uranium",
            "aluminum",
            "copper",
            "开采专业及辅助性活动",
            "一般金属及矿石",
            "金属制品",
            "黄金及贵金属",
            "贵金属",
            "有色金属",
            "小金属",
            "采掘",
            "采矿",
            "钢铁",
            "黄金",
        ),
    ),
    IndustryRule(
        "industry:chemicals",
        "sector:materials",
        "化工",
        "Chemicals",
        (
            "chemicals",
            "chemical",
            "基础化工",
            "化学原料",
            "化学制品",
            "化学纤维制造业",
            "化肥",
            "农药",
            "化纤",
            "塑料制品",
            "橡胶制品",
            "化工",
        ),
    ),
    IndustryRule(
        "industry:construction_materials",
        "sector:materials",
        "建筑材料",
        "Construction Materials",
        (
            "construction materials",
            "building materials",
            "非金属矿物制品业",
            "水泥建材",
            "装修建材",
            "玻璃玻纤",
            "建筑材料",
            "水泥",
        ),
    ),
    IndustryRule(
        "industry:forest_products",
        "sector:materials",
        "造纸与林业",
        "Paper & Forest Products",
        (
            "paper lumber",
            "paper & paper products",
            "forest products",
            "packaging & containers",
            "印刷和记录媒介复制业",
            "造纸印刷",
            "包装材料",
            "造纸",
            "林业",
        ),
    ),
    IndustryRule(
        "industry:diversified_materials",
        "sector:materials",
        "综合原材料",
        "Diversified Materials",
        ("industrial materials", "原材料", "基础材料", "materials"),
    ),
    IndustryRule(
        "industry:aerospace_defense",
        "sector:industrials",
        "航空航天与国防",
        "Aerospace & Defense",
        (
            "aerospace & defense",
            "aerospace",
            "defense",
            "航空航天",
            "航天航空",
            "航空工业",
            "国防军工",
            "军工",
            "卫星制造",
            "航天",
        ),
    ),
    IndustryRule(
        "industry:machinery",
        "sector:industrials",
        "机械设备",
        "Machinery",
        (
            "industrial machinery",
            "machinery",
            "industrial equipment",
            "manufacturing - tools & accessories",
            "仪器仪表制造业",
            "工程机械",
            "通用设备",
            "专用设备",
            "机械行业",
            "机械设备",
            "工业设备",
        ),
    ),
    IndustryRule(
        "industry:electrical_equipment",
        "sector:industrials",
        "电气设备",
        "Electrical Equipment",
        (
            "electrical equipment & parts",
            "electrical equipment",
            "电气机械和器材制造业",
            "电网设备",
            "电机",
            "电气设备",
            "电源设备",
        ),
    ),
    IndustryRule(
        "industry:construction_engineering",
        "sector:industrials",
        "建筑与工程",
        "Construction & Engineering",
        (
            "engineering & construction",
            "residential construction",
            "construction",
            "industrial engineering",
            "industrial - infrastructure operations",
            "工业工程",
            "工程建设",
            "装修装饰",
            "建筑",
            "建筑工程",
        ),
    ),
    IndustryRule(
        "industry:transportation",
        "sector:industrials",
        "交通运输",
        "Transportation",
        (
            "airlines, airports & air services",
            "railroads",
            "transportation",
            "trucking",
            "运输仓储",
            "工用运输",
            "航空机场",
            "铁路公路",
            "交通运输",
            "航空公司",
            "铁路",
        ),
    ),
    IndustryRule(
        "industry:shipping",
        "sector:industrials",
        "航运与物流",
        "Shipping & Logistics",
        (
            "integrated freight & logistics",
            "marine shipping",
            "shipping",
            "logistics",
            "多式联运和运输代理业",
            "水上运输业",
            "航运港口",
            "航运",
            "物流",
            "港口",
        ),
    ),
    IndustryRule(
        "industry:business_services",
        "sector:industrials",
        "商业与专业服务",
        "Business Services",
        (
            "staffing & employment services",
            "security & protection services",
            "specialty business services",
            "industrial distribution",
            "waste management",
            "consulting services",
            "rental & leasing services",
            "industrial - pollution & treatment controls",
            "business equipment & supplies",
            "environmental services",
            "support services",
            "科学研究和技术服务业",
            "水利、环境和公共设施管理业",
            "生态保护和环境治理业",
            "专业技术服务业",
            "公共设施管理业",
            "科研服务",
            "商务服务",
            "支援服务",
            "工用支援",
            "专业服务",
            "商业服务",
            "环保行业",
            "环保",
        ),
    ),
    IndustryRule(
        "industry:diversified_industrials",
        "sector:industrials",
        "综合工业",
        "Diversified Industrials",
        ("conglomerates", "manufacturing", "综合企业", "综合工业", "制造业", "综合", "industrials"),
    ),
    IndustryRule(
        "industry:automobiles",
        "sector:consumer_discretionary",
        "汽车",
        "Automobiles",
        (
            "auto manufacturers",
            "auto - recreational vehicles",
            "automotive",
            "automobile",
            "汽车整车",
            "汽车制造",
            "新能源车",
            "汽车",
        ),
    ),
    IndustryRule(
        "industry:auto_parts",
        "sector:consumer_discretionary",
        "汽车零部件",
        "Auto Parts",
        ("auto parts", "汽车零部件", "汽车配件"),
    ),
    IndustryRule(
        "industry:retail",
        "sector:consumer_discretionary",
        "零售",
        "Retail",
        (
            "specialty retail",
            "apparel retail",
            "auto dealerships",
            "professional retail",
            "department stores",
            "专业零售",
            "商业百货",
            "批发业",
            "零售业",
            "零售",
            "电商",
        ),
    ),
    IndustryRule(
        "industry:restaurants_leisure",
        "sector:consumer_discretionary",
        "餐饮旅游与休闲",
        "Restaurants, Travel & Leisure",
        (
            "gambling, resorts & casinos",
            "travel services",
            "travel lodging",
            "restaurants",
            "leisure",
            "旅游及消闲设施",
            "旅游酒店",
            "餐饮",
            "酒店",
            "休闲",
        ),
    ),
    IndustryRule(
        "industry:apparel",
        "sector:consumer_discretionary",
        "纺织服饰",
        "Apparel & Textiles",
        (
            "apparel manufacturers",
            "manufacturing - textiles",
            "luxury goods",
            "apparel",
            "textile",
            "纺织及服饰",
            "纺织服装",
            "服装家纺",
            "纺织业",
        ),
    ),
    IndustryRule(
        "industry:home_goods",
        "sector:consumer_discretionary",
        "家居与家电",
        "Home Goods & Appliances",
        (
            "furnishings, fixtures & appliances",
            "home improvement",
            "furnishings",
            "household appliances",
            "家具制造业",
            "家庭电器及用品",
            "家电行业",
            "家用电器",
            "家居用品",
        ),
    ),
    IndustryRule(
        "industry:consumer_services",
        "sector:consumer_discretionary",
        "消费服务",
        "Consumer Services",
        (
            "education & training services",
            "personal services",
            "personal products & services",
            "consumer services",
            "居民服务",
            "教育",
            "消费服务",
        ),
    ),
    IndustryRule(
        "industry:diversified_consumer_discretionary",
        "sector:consumer_discretionary",
        "综合可选消费",
        "Diversified Consumer Discretionary",
        ("consumer cyclical", "可选消费"),
    ),
    IndustryRule(
        "industry:food_beverage",
        "sector:consumer_staples",
        "食品饮料",
        "Food & Beverage",
        (
            "packaged foods",
            "food distribution",
            "beverages",
            "酒、饮料和精制茶制造业",
            "食品制造业",
            "food",
            "食物饮品",
            "食品饮料",
            "酿酒行业",
            "食品加工",
            "饮料乳品",
            "白酒",
        ),
    ),
    IndustryRule(
        "industry:agriculture",
        "sector:consumer_staples",
        "农业",
        "Agriculture",
        (
            "agricultural farm products",
            "agricultural inputs",
            "agricultural - commodities/milling",
            "farm products",
            "农业产品",
            "农牧饲渔",
            "农林牧渔",
            "种植业",
            "畜牧业",
            "养殖业",
            "农业",
        ),
    ),
    IndustryRule(
        "industry:household_personal_products",
        "sector:consumer_staples",
        "家庭与个人用品",
        "Household & Personal Products",
        ("household & personal products", "tobacco", "家庭与个人用品", "日用化工", "美容护理"),
    ),
    IndustryRule(
        "industry:staples_retail",
        "sector:consumer_staples",
        "必选消费零售",
        "Consumer Staples Retail",
        (
            "consumer staples retail",
            "discount stores",
            "grocery stores",
            "消费者主要零售商",
            "商贸零售",
        ),
    ),
    IndustryRule(
        "industry:diversified_consumer_staples",
        "sector:consumer_staples",
        "综合必选消费",
        "Diversified Consumer Staples",
        ("consumer defensive", "必选消费"),
    ),
    IndustryRule(
        "industry:pharmaceuticals",
        "sector:health_care",
        "制药",
        "Pharmaceuticals",
        (
            "drug manufacturers - specialty & generic",
            "drug manufacturers",
            "medical - pharmaceuticals",
            "pharmaceuticals",
            "pharmaceutical",
            "医药制造业",
            "医药商业",
            "化学制药",
            "中药",
            "药品",
            "制药",
            "医药",
        ),
    ),
    IndustryRule(
        "industry:biotechnology",
        "sector:health_care",
        "生物科技",
        "Biotechnology",
        ("biotechnology", "biotech", "生物制品", "生物科技"),
    ),
    IndustryRule(
        "industry:medical_devices",
        "sector:health_care",
        "医疗器械",
        "Medical Devices",
        (
            "medical - instruments & supplies",
            "medical instruments",
            "medical - devices",
            "medical devices",
            "医疗器械",
            "医疗设备",
        ),
    ),
    IndustryRule(
        "industry:healthcare_services",
        "sector:health_care",
        "医疗服务",
        "Health Care Services",
        (
            "medical - diagnostics & research",
            "medical - care facilities",
            "medical - equipment & services",
            "medical - distribution",
            "medical - specialties",
            "healthcare plans",
            "healthcare providers",
            "healthcare services",
            "other healthcare",
            "其他医疗保健",
            "医疗服务",
            "医疗美容",
            "卫生",
        ),
    ),
    IndustryRule(
        "industry:diversified_healthcare",
        "sector:health_care",
        "综合医疗健康",
        "Diversified Health Care",
        ("healthcare", "医疗保健", "医疗健康"),
    ),
    IndustryRule(
        "industry:banks",
        "sector:financials",
        "银行",
        "Banks",
        ("banks - diversified", "banks - regional", "banking", "banks", "银行"),
    ),
    IndustryRule(
        "industry:insurance",
        "sector:financials",
        "保险",
        "Insurance",
        (
            "insurance - property & casualty",
            "insurance - diversified",
            "insurance - reinsurance",
            "insurance - brokers",
            "insurance - life",
            "insurance",
            "保险",
        ),
    ),
    IndustryRule(
        "industry:capital_markets",
        "sector:financials",
        "资本市场",
        "Capital Markets",
        (
            "financial - capital markets",
            "investment - banking & investment services",
            "financial - data & stock exchanges",
            "capital markets",
            "brokerage",
            "证券行业",
            "证券",
            "券商",
            "投行",
        ),
    ),
    IndustryRule(
        "industry:asset_management",
        "sector:financials",
        "资产管理",
        "Asset Management",
        ("asset management", "investment managers", "资产管理", "基金管理"),
    ),
    IndustryRule(
        "industry:credit_services",
        "sector:financials",
        "信贷服务",
        "Credit Services",
        (
            "financial - credit services",
            "financial - mortgages",
            "credit services",
            "mortgage finance",
            "信贷服务",
            "消费金融",
        ),
    ),
    IndustryRule(
        "industry:diversified_financials",
        "sector:financials",
        "综合金融",
        "Diversified Financials",
        (
            "financial - conglomerates",
            "other financial",
            "其他金融",
            "多元金融",
            "综合金融",
        ),
    ),
    IndustryRule(
        "industry:special_purpose",
        "sector:financials",
        "特殊目的公司",
        "Special Purpose Companies",
        (
            "shell companies",
            "blank check",
            "special purpose acquisition",
            "spac",
            "壳公司",
            "特殊目的公司",
        ),
    ),
    IndustryRule(
        "industry:semiconductors",
        "sector:information_technology",
        "半导体",
        "Semiconductors",
        (
            "semiconductor equipment & materials",
            "semiconductors",
            "semiconductor",
            "半导体",
            "芯片",
        ),
    ),
    IndustryRule(
        "industry:software",
        "sector:information_technology",
        "软件",
        "Software",
        (
            "software - infrastructure",
            "software - application",
            "application software",
            "software services",
            "软件服务",
            "软件开发",
            "软件",
            "saas",
        ),
    ),
    IndustryRule(
        "industry:hardware",
        "sector:information_technology",
        "硬件与设备",
        "Technology Hardware",
        (
            "hardware, equipment & parts",
            "computer hardware",
            "communication equipment",
            "technology hardware",
            "technology distributors",
            "computer equipment",
            "资讯科技器材",
            "计算机设备",
            "通信设备",
            "电脑硬件",
            "硬件",
        ),
    ),
    IndustryRule(
        "industry:electronic_components",
        "sector:information_technology",
        "电子元件",
        "Electronic Components",
        (
            "electronic components",
            "electronic gaming & multimedia",
            "consumer electronics",
            "electronic equipment",
            "消费电子",
            "光学光电子",
            "电子元件",
            "元件",
            "电子设备",
        ),
    ),
    IndustryRule(
        "industry:it_services",
        "sector:information_technology",
        "信息技术服务",
        "Information Technology Services",
        (
            "medical - healthcare information services",
            "information technology services",
            "it services",
            "数据中心",
            "信息技术服务",
            "数字化服务",
        ),
    ),
    IndustryRule(
        "industry:diversified_technology",
        "sector:information_technology",
        "综合信息技术",
        "Diversified Technology",
        ("technology", "信息技术", "科技"),
    ),
    IndustryRule(
        "industry:internet",
        "sector:communication_services",
        "互联网服务",
        "Internet Services",
        (
            "internet content & information",
            "interactive media",
            "internet services",
            "互联网服务",
            "互联网",
            "网络服务",
        ),
    ),
    IndustryRule(
        "industry:media_entertainment",
        "sector:communication_services",
        "传媒娱乐",
        "Media & Entertainment",
        (
            "advertising agencies",
            "broadcasting",
            "publishing",
            "entertainment",
            "media",
            "文化、体育和娱乐业",
            "媒体及娱乐",
            "文化传播",
            "文化传媒",
            "传媒娱乐",
            "游戏",
            "传媒",
        ),
    ),
    IndustryRule(
        "industry:telecom",
        "sector:communication_services",
        "电信",
        "Telecommunication",
        (
            "telecommunications services",
            "telecommunication",
            "telecom",
            "电信运营",
            "通信服务",
            "电讯",
            "电信",
        ),
    ),
    IndustryRule(
        "industry:diversified_communication",
        "sector:communication_services",
        "综合通信服务",
        "Diversified Communication Services",
        ("communication services", "通信服务"),
    ),
    IndustryRule(
        "industry:electric_utilities",
        "sector:utilities",
        "电力",
        "Electric Utilities",
        (
            "regulated electric",
            "independent power producers",
            "electric utilities",
            "电力行业",
            "火力发电",
            "电力",
            "公用事业",
        ),
    ),
    IndustryRule(
        "industry:gas_water_utilities",
        "sector:utilities",
        "燃气与水务",
        "Gas & Water Utilities",
        (
            "regulated gas",
            "regulated water",
            "gas utilities",
            "water utilities",
            "水电煤气",
            "燃气",
            "水务",
        ),
    ),
    IndustryRule(
        "industry:renewable_utilities",
        "sector:utilities",
        "可再生能源公用事业",
        "Renewable Utilities",
        ("renewable utilities", "可再生能源公用事业"),
    ),
    IndustryRule(
        "industry:real_estate",
        "sector:real_estate",
        "房地产开发运营",
        "Real Estate",
        (
            "real estate - development",
            "real estate development",
            "地产发展商",
            "房地产开发",
            "房地产",
            "地产",
        ),
    ),
    IndustryRule(
        "industry:real_estate_services",
        "sector:real_estate",
        "房地产服务",
        "Real Estate Services",
        ("real estate - services", "real estate services", "物业服务", "房地产服务"),
    ),
    IndustryRule(
        "industry:reits",
        "sector:real_estate",
        "房地产投资信托",
        "REITs",
        (
            "reit - healthcare facilities",
            "reit -",
            "real estate investment trust",
            "房地产信托",
            "reits",
            "reit",
        ),
    ),
    IndustryRule(
        "industry:cryptocurrency",
        "sector:digital_assets",
        "加密货币",
        "Cryptocurrency",
        ("cryptocurrency", "crypto", "加密货币", "数字货币", "区块链"),
    ),
)


_SECTOR_DEFAULTS = {
    "sector:energy": "industry:diversified_energy",
    "sector:materials": "industry:diversified_materials",
    "sector:industrials": "industry:diversified_industrials",
    "sector:consumer_discretionary": "industry:diversified_consumer_discretionary",
    "sector:consumer_staples": "industry:diversified_consumer_staples",
    "sector:health_care": "industry:diversified_healthcare",
    "sector:financials": "industry:diversified_financials",
    "sector:information_technology": "industry:diversified_technology",
    "sector:communication_services": "industry:diversified_communication",
    "sector:utilities": "industry:electric_utilities",
    "sector:real_estate": "industry:real_estate",
    "sector:digital_assets": "industry:cryptocurrency",
}


def _normalize(value: str) -> str:
    return re.sub(r"[^a-z0-9\u3400-\u9fff]+", "", unicodedata.normalize("NFKC", value).casefold())


def all_industries() -> list[IndustryRef]:
    output = list(SECTORS)
    output.extend(
        IndustryRef(
            industry_id=item.industry_id,
            parent_id=item.sector_id,
            level=2,
            name_zh=item.name_zh,
            name_en=item.name_en,
            aliases=list(item.aliases),
        )
        for item in RULES
    )
    return output


def normalize_industry(raw_sector: str = "", raw_industry: str = "") -> tuple[str, str]:
    normalized_industry = _normalize(raw_industry)
    normalized_sector = _normalize(raw_sector)
    if not normalized_industry and not normalized_sector:
        return "", ""
    aliases = sorted(
        (
            (len(normalized_alias), rule, normalized_alias)
            for rule in RULES
            for alias in rule.aliases
            if (normalized_alias := _normalize(alias))
        ),
        key=lambda item: item[0],
        reverse=True,
    )
    for source_text in (normalized_industry, normalized_sector):
        if not source_text:
            continue
        for _, rule, alias in aliases:
            if alias in source_text:
                return rule.sector_id, rule.industry_id
    text = f"{normalized_sector}{normalized_industry}"
    for sector in SECTORS:
        terms = [sector.name_zh, sector.name_en, *sector.aliases]
        if any(_normalize(term) in text for term in terms):
            return sector.industry_id, _SECTOR_DEFAULTS[sector.industry_id]
    return "", ""


def industries_mentioned(text: str) -> list[str]:
    normalized = _normalize(text)
    matches: list[str] = []
    for item in RULES:
        if item.industry_id in _SECTOR_DEFAULTS.values():
            continue
        if any(_normalize(alias) in normalized for alias in item.aliases):
            matches.append(item.industry_id)
    return list(dict.fromkeys(matches))
