use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "ultrasecretkey"
  limiter: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

engines:
  - name: duckduckgo
    disabled: true
